-- MySQL Script generated by MySQL Workbench
-- 03/07/17 00:32:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`oficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oficio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_oficio` INT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oficio_categoria_idx` (`id_oficio` ASC),
  CONSTRAINT `fk_oficio_categoria`
    FOREIGN KEY (`id_oficio`)
    REFERENCES `mydb`.`oficio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nacionalidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuadrilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadrilla` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `encargado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_encargado_cuadrilla_idx` (`encargado` ASC),
  CONSTRAINT `fk_encargado_cuadrilla`
    FOREIGN KEY (`encargado`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuit` BIGINT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `poliza` BIGINT NULL,
  `legajo` BIGINT NULL,
  `jornal` DOUBLE NULL,
  `nacimiento` DATETIME NULL,
  `domicilio` VARCHAR(90) NULL,
  `id_nacionalidad` INT NULL,
  `tipo_contrato` INT NULL,
  `id_oficio` INT NOT NULL,
  `id_categoria` INT NULL,
  `id_cuadrilla` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oficio_idx` (`id_oficio` ASC),
  INDEX `fk_categoria_idx` (`id_categoria` ASC),
  INDEX `fk_contrato_idx` (`tipo_contrato` ASC),
  INDEX `fk_nacionalidad_idx` (`id_nacionalidad` ASC),
  INDEX `fk_cuadrilla_idx` (`id_cuadrilla` ASC),
  CONSTRAINT `fk_oficio`
    FOREIGN KEY (`id_oficio`)
    REFERENCES `mydb`.`oficio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato`
    FOREIGN KEY (`tipo_contrato`)
    REFERENCES `mydb`.`tipo_contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nacionalidad`
    FOREIGN KEY (`id_nacionalidad`)
    REFERENCES `mydb`.`nacionalidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuadrilla`
    FOREIGN KEY (`id_cuadrilla`)
    REFERENCES `mydb`.`cuadrilla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NULL,
  `jefeobra` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jefe_obra_idx` (`jefeobra` ASC),
  CONSTRAINT `fk_jefe_obra`
    FOREIGN KEY (`jefeobra`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(120) NULL,
  `cuit` VARCHAR(45) NULL,
  `empresacol` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa_obra` (
  `id_empresa` INT NOT NULL,
  `id_obra` INT NOT NULL,
  PRIMARY KEY (`id_empresa`, `id_obra`),
  INDEX `fk_obra_idx` (`id_obra` ASC),
  CONSTRAINT `fk_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra`
    FOREIGN KEY (`id_obra`)
    REFERENCES `mydb`.`obra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cierre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cierre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NULL,
  `anio` INT NULL,
  `quincena` INT NULL,
  `horas` VARCHAR(45) NULL,
  `jornal` DOUBLE NULL,
  `extra` DOUBLE NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimientos_persona_idx` (`id_persona` ASC),
  CONSTRAINT `fk_movimientos_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado` INT NULL,
  `fecha_hora` DATETIME NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_empleado_idx` (`empleado` ASC),
  INDEX `fk_estado_registro_idx` (`estado` ASC),
  CONSTRAINT `fk_registro_empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado_registro`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`estado_registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NULL,
  `password` VARCHAR(90) NULL,
  `estado` TINYINT NULL,
  `empresa` INT NULL,
  `perfil` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empresa_idx` (`empresa` ASC),
  INDEX `fk_usuario_perfil_idx` (`perfil` ASC),
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`empresa`)
    REFERENCES `mydb`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil`)
    REFERENCES `mydb`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_contacto` INT NULL,
  `dato` VARCHAR(45) NULL,
  `empleado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_contacto_idx` (`tipo_contacto` ASC),
  INDEX `fk_contacto_empleado_idx` (`empleado` ASC),
  CONSTRAINT `fk_tipo_contacto`
    FOREIGN KEY (`tipo_contacto`)
    REFERENCES `mydb`.`tipo_contacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacto_empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_bancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_bancarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banco` INT NULL,
  `cbu` BIGINT NULL,
  `numero_cuenta` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banco_idx` (`banco` ASC),
  CONSTRAINT `fk_banco`
    FOREIGN KEY (`banco`)
    REFERENCES `mydb`.`banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banco_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banco_persona` (
  `id_banco` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_banco`, `id_persona`),
  INDEX `fk_persona_banco_idx` (`id_persona` ASC),
  CONSTRAINT `fk_banco_persona`
    FOREIGN KEY (`id_banco`)
    REFERENCES `mydb`.`datos_bancarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_banco`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacto_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto_persona` (
  `id_persona` INT NOT NULL,
  `id_contacto` INT NOT NULL,
  PRIMARY KEY (`id_persona`, `id_contacto`),
  INDEX `fk_contacto_persona_idx` (`id_contacto` ASC),
  CONSTRAINT `fk_contacto_persona`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `mydb`.`contacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_contacto`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
